name: Create release
on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
          token: ${{secrets.GIT_PUSH_TOKEN}}
      - name: Create release commit
        run: |
          sudo apt-get update
          sudo apt-get install --no-install-recommends -y git-buildpackage
          export DEBEMAIL="dev@radxa.com"
          export DEBFULLNAME='"Radxa Computer Co., Ltd"'
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          make dch
      - name: Test
        run: |
          sudo apt-get update
          sudo apt-get build-dep --no-install-recommends -y .
          sudo apt-get full-upgrade --no-install-recommends -y build-essential \
          git devscripts lintian wget
          wget https://github.com/airockchip/rknn-toolkit2/raw/master/rknn-toolkit2/packages/requirements_cp310-1.6.0.txt
          wget https://github.com/airockchip/rknn-toolkit2/raw/master/rknn-toolkit2/packages/rknn_toolkit2-1.6.0+81f21f4d-cp310-cp310-linux_x86_64.whl
          pip3 install -r requirements_cp310-1.6.0.txt
          pip3 install rknn_toolkit2-1.6.0+81f21f4d-cp310-cp310-linux_x86_64.whl
          make all deb
      - name: Push
        run: |
          git push
